name: Reuse other workflow

on:
  workflow_dispatch:
    
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with: 
      who-to-greet: 'Chuck Norris'

  use-output:
    runs-on: ubuntu-latest
      needs: [call-workflow]
      steps:
        -run: echo "Timestamp was {{ needs.call-workflow.outputs.current-time }}"
